spring:
  application:
    name: posto-combustivel
  datasource:
    url: ${JDBC_URL:jdbc:h2:file:./db}
    username: ${JDBC_USERNAME:sa}
    password:
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never
  servlet:
    context-path: /posto-combustivel