CREATE TABLE BOMBA_COMBUSTIVEL (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    id_tipo_combustivel VARCHAR(255) NOT NULL
);

ALTER TABLE BOMBA_COMBUSTIVEL ADD CONSTRAINT FK_TIPO_COMBUSTIVEL
FOREIGN KEY (id_tipo_combustivel) REFERENCES TIPO_COMBUSTIVEL(id);